on: push
name: SonarQube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.organization=1corp 
           -Dsonar.projectKey=io.releaseiq:riqpubsub 
           -Dsonar.host.url=${{ secrets.SONAR_HOST }} 
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
